### ISSUE TITLE
Just a question

### ISSUE THREAD

**Issue by JMCPH** [UPetersen/LibreMonitor#18]
Hi!

I'm a IT student at the IT-university of Copenhagen. I'm about to write my master thesis about diabetes and how technology can support parents with children diagnosed with diabetes.

I have a question regarding the code which scans the NFC tag from the Freestyle Libre Sensor. 

I can't seem to find the files for the Arduino, where the actual scanning and processing of the NFC dataset from the sensor to the Arduino is done.

The goal is to develop an iOS application, which can scan the NFC tag directly from the Freestyle Libre Sensor, instead of sending it over bluetooth.

Best Regards,

Jakob

**Comment by UPetersen** [comment]
Hi Jakob,

the original Arduino code is in the [top directory](https://github.com/UPetersen/LibreMonitor.) of the LibreMonitor repository, see the *.ino files and the library in *.zip.

I switched to platformio IDE some time ago and then put the Arduino code into a separate repository: [https://github.com/UPetersen/LibreMonitorRFduino](https://github.com/UPetersen/LibreMonitorRFduino). So this is the best starting point.
If you plan to scan directly, it should be sufficient to read the first 43 blocks of FRAM data and the tag ID. 

Please use the [swift4](https://github.com/UPetersen/LibreMonitor/tree/Swift4) branch for any iOS coding as it contains the most current iOS code.

All the best,

Uwe
