### ISSUE TITLE
Quick Question

### ISSUE THREAD

**Issue by balasuper** [UPetersen/LibreMonitor#24]
This is regarding reuse  the sensor but with another ADC device . Since the clever bits of libre are the pt-ir skin sensor , and the current measurement pads are exposed ,is it possible to read them using another current measurement op amp and ADC?

Since the sensor just wears out when the reagents are used up (and it seems to be software locked to 14 days) would interfacing directly with the sensor be a viable way to extend the life of sensor?

My embodiment of this idea is to use a  hacked /normal finger prick  meter to actually measure the sensor still stuck to the skin.

Sure its not a flash CGM  but its 90% there. Apologies in advance if not correct forum.

**Comment by UPetersen** [comment]
Dear balasuper,
I personally would refrain from any such efforts. There is software available to read the sensor and some of which extend sensor life by 12 hours, see e.g. [Juggluco](www.jugluco.com) which is open source. I have not heard of anyone going beyond 12 hours.
