### ISSUE TITLE
Parts needed for a LibreMonitor are - broken battery link

### ISSUE THREAD

**Issue by clvsjr9** [UPetersen/LibreMonitor#5]
The lipo link indicated is broken

**Comment by UPetersen** [comment]
I still use a 100 mAh lipo that I took out of a little model helicopter. It lasts a full day from early morning to late evening with the transfer interval set to two minutes. To my understanding any lipo with 110 mAh or more should do. If you want a longer time you could go higher, e.g. 200 mAh. A higher discharge rate is probably better and enables using a faster charger. I corrected the link in the readme for a lipo that should be appropriate.
