### ISSUE TITLE
A series of build errors

### ISSUE THREAD

**Issue by erikstr** [UPetersen/LibreMonitor#9]
I am trying to build the iOS app straight out of the fresh downloaded sources, but getting a lot of errors. Here is a screenshot of them. What am I doing wrong?
![bildschirmfoto 2017-03-09 um 18 52 03](https://cloud.githubusercontent.com/assets/619282/23763469/0797fcf4-04fa-11e7-9ce2-e5f0f040073e.png)

**Comment by UPetersen** [comment]
Hi Erik,

have you installed cocoapods? There are some third party libraries used, that require cocoapods. For installation see [https://cocoapods.org](https://cocoapods.org). From then on you have to open  LibreMonitor.xcworkspace instead of LibreMonitor.xcodeproj.

**Comment by erikstr** [comment]
No, I hadn't :( sorry that I didn't pay attention to this. 
However, even with the Charts lib installed, I still get compile errors :((
![bildschirmfoto 2017-03-09 um 21 24 21](https://cloud.githubusercontent.com/assets/619282/23769260/26708f0a-050f-11e7-9833-4f278890b9b3.png)
![bildschirmfoto 2017-03-09 um 21 24 33](https://cloud.githubusercontent.com/assets/619282/23769271/2c9656c6-050f-11e7-9f9d-2d7d206574b9.png)

**Comment by erikstr** [comment]
Here are the full details:
![bildschirmfoto 2017-03-09 um 21 30 17](https://cloud.githubusercontent.com/assets/619282/23769437/ad6e1428-050f-11e7-8515-54d3d97ffaa5.png)

**Comment by UPetersen** [comment]
Mmmh, that leaves me scratching my head. I just downloaded the code from GitHub myself, ran "pod install" in the directory, opened the workspace file and compiled with simulator vor iPhone SE and it runs. I use Xcode 8.2.1.
![compiledoniphonese](https://cloud.githubusercontent.com/assets/10375483/23770051/d52ed4a0-0511-11e7-9108-99d57d296bf4.jpeg)

**Comment by UPetersen** [comment]
Have you tried to clean the build (Product and then "alt" - "Clean Build Folder". Sometimes that helps.

**Comment by UPetersen** [comment]
Also worth a try (last answer): [swiftc failed with exit code 1](http://stackoverflow.com/questions/41203153/swiftc-failed-with-exit-code-1).

**Comment by UPetersen** [comment]
Or this one: [ERROR swiftc failed with exit code 1](http://stackoverflow.com/questions/38496582/error-swiftc-failed-with-exit-code-1).

**Comment by erikstr** [comment]
8.2.1 here as well. Yes, I clean every time. I suspect, that I am doing something wrong with the Charts lib. The instruction there says "Drag the Charts.xcodeproj to your project". However you can't drag just this file leaving the whole folder structure behind, so I download the zip, unpack it and include the lib from there to the target.

**Comment by erikstr** [comment]
I'll switch to my MacBook now and start over from scratch ...

**Comment by UPetersen** [comment]
I never dragged the charts lib. I installed it via cocoapods. Try this: Once you have cocoapods installed, just download the complete LibreMonitor-project again. Open a shell, change into the LibreMonitor directory and there type "pod install". Then open the workspace file with Xcode and compile.

**Comment by erikstr** [comment]
Success! 
It turns out that the downloaded charts lib I previously linked is for macOS only, no iOS. Now the app compiles and runs on the iPhone. The RFduino connects also fine but I am getting no readings :( What worries me even more is that no BM019 ID is shown as when there is no connection between the RFduino and the BM019 module. The ino sketch compiled and loaded fine. How could I investigate this problem now? I checked the wiring, looks good. But the BM019 LED is lighting red. Is this normal?

**Comment by erikstr** [comment]
Here is a screenshot:
![img_1346](https://cloud.githubusercontent.com/assets/619282/23771943/6f093c80-0519-11e7-95c0-7f39efeb600e.PNG)

**Comment by UPetersen** [comment]
This looks good. The right light on the BM019 is right. And you have a bluetooth connection to the RFduino. Now you should check, wether you get valid signals on the Arduino side, best by using the serial monitor. Set the 

`#define DEBUG `

and you should see some hex values. To reduce your waiting times, you can reduce the sleep time for tests, e.g. by setting it to 20 s:

`const uint64_t SLEEP_DURATION = 20000;  // Duration of Simblee ultra low power mode in ms`

Another important thing is to have the SPI wiring correct. If you wired as depicted in the pictures, you have to change the RFduino pins in software. This is done in the variant.h file. In my case this file is located (dependent on the Simblee/RFduino version) in

/Users/[my user name]/Library/Arduino15/packages/Simblee/hardware/Simblee/1.0.0/variants/Simblee or
/Users/[my user name]/Library/Arduino15/packages/RFduino/hardware/RFduino/2.3.3/variants

In this file set the defines for the SPI pins as follows:

```
///         #define PIN_SPI_SS           (3u)
///         #define PIN_SPI_MOSI         (5u)
///         #define PIN_SPI_MISO         (4u)
///         #define PIN_SPI_SCK          (6u)
```

I also sent you a private note on gitter.
